# Generated by Django 6.1.1 on 2026-09-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item pedido', 'verbose_name_plural': 'Itens pedido'},
        ),
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'verbose_name': 'Perfil cliente', 'verbose_name_plural': 'Perfis clientes'},
        ),
        migrations.AlterModelOptions(
            name='perfilvendedor',
            options={'verbose_name': 'Perfil vendedor', 'verbose_name_plural': 'Perfis vendedores'},
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilvendedor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
