# Generated by Django 6.1.1 on 2026-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_itempedido_options_alter_perfilcliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='marketplace.tag'),
        ),
    ]
