# Generated by Django 6.1.1 on 2026-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_produto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
